name: 'checkout-and-setup'
description: 'action for compile, check, build and test'
runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Chmode gradlew
      run: chmod +x ./gradlew