name: Generate Coverage
on:
  push:
jobs:
  generate-coverage:
    name: Generate and deploy coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Chmode gradlew
        run: chmod +x ./gradlew
      - name: Generate Jacoco report
        run: ./gradlew test jacocoTestReport
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          override_pr: ${{ github.event.number }}
          override_sha: ${{ github.event.pull_request.head.sha }}
          functionalities:
            recursesubs: true
          fail_ci_if_error: true
