name: deleteme-fcla-workflow
on: push
jobs:
  generate-and-deploy-project-doc:
    name: generate-and-deploy-project-doc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Chmode gradlew
        run: chmod +x ./gradlew
      - name: Create empty folder
        run: mkdir emptyFolder
      - name: Empty gh-pages
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: emptyFolder
      - name: Generate Dokka docs
        run: ./gradlew dokkaHtml
      - name: Deploy Dokka docs
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: build/dokka/html
          target-folder: dokka
      - name: Generate Jacoco report
        run: ./gradlew test jacocoTestReport
      - name: Deploy Jacoco report
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: build/reports/jacoco/test/html
          target-folder: jacoco