name: deleteme-fcla-workflow
on:
  push:
    branches:
      - main
      - develop
jobs:
  generate-and-deploy-coverage:
    name: generate-and-deploy-coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Chmode gradlew
        run: chmod +x ./gradlew
      - name: Generate Jacoco report
        run: ./gradlew test jacocoTestReport
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
  generate-and-deploy-project-doc:
    name: generate-and-deploy-project-doc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Chmode gradlew
        run: chmod +x ./gradlew
      - name: Create empty folder
        run: mkdir emptyFolder
      - name: Empty gh-pages
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: emptyFolder
      - name: Generate Dokka docs
        run: ./gradlew dokkaHtml
      - name: Deploy Dokka docs
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: build/dokka/html